# Generated by Django 5.2.4 on 2025-08-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Email Verification Code'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verification_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email Verification Code Timestamp'),
        ),
    ]
