# Generated by Django 5.2.4 on 2025-08-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='Phone Number (E.164 format)'),
        ),
    ]
