# Generated by Django 5.2.4 on 2025-08-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_featureinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profile Photo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='display_name_preference',
            field=models.CharField(choices=[('USERNAME', 'Username Only'), ('FIRST_NAME_INITIAL', 'First Name & Last Initial')], default='USERNAME', max_length=20, verbose_name='Review Display Name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='show_avatar_on_reviews',
            field=models.BooleanField(default=False, help_text='If checked, your avatar will be publicly visible next to your reviews.', verbose_name='Show profile picture on reviews'),
        ),
    ]
