# Generated by Django 5.2.4 on 2025-08-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Phone Number (E.164 format)'),
        ),
    ]
