# Generated by Django 5.2.4 on 2025-08-12 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_email_verification_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verification_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_verification_timestamp',
        ),
    ]
