# Generated by Django 5.2.4 on 2025-08-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_lockout_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Phone Verification Lockout Until'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_verification_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
