# Generated by Django 5.2.4 on 2025-08-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_avatar_customuser_display_name_preference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='show_avatar_on_reviews',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Avatar Path'),
        ),
    ]
