# Generated by Django 5.2.4 on 2025-09-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_show_avatar_on_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_name_preference',
            field=models.CharField(choices=[('USERNAME', 'Username Only'), ('FIRST_NAME_INITIAL', 'First Name & Last Initial')], default='USERNAME', max_length=20, verbose_name='Review Display Name (Choose an option)'),
        ),
    ]
