# Generated by Django 5.2.4 on 2025-09-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_display_name_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_name_preference',
            field=models.CharField(choices=[('USERNAME', 'Username'), ('INITIALS', 'First Name & Last Initial')], default='USERNAME', max_length=20, verbose_name='Review Display Name (Choose an option)'),
        ),
    ]
