# Generated by Django 5.2.4 on 2025-09-26 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_display_name_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp Number (Optional)')),
                ('category', models.CharField(choices=[('GENERAL', 'General Feedback'), ('IDEA', 'I have an idea for a new feature'), ('BUG', 'I found a bug or incorrect information'), ('PARTNER', 'I am a property manager or owner'), ('OTHER', 'Something else')], default='GENERAL', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
