# Generated by Django 5.2.4 on 2025-10-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='welcome_email_sent',
            field=models.BooleanField(default=False, help_text='Indicates if the welcome email has been sent to the user.'),
        ),
    ]
