# Generated by Django 5.2.4 on 2025-12-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_welcome_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lazy_registration_complete',
            field=models.BooleanField(default=False, help_text='Indicates if the user has seen the review success page and completed the lazy registration.'),
        ),
    ]
