# Generated by Django 5.2.4 on 2025-12-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_lazy_registration_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='lazy_registration_complete',
            field=models.BooleanField(default=True, help_text='Indicates if the user has seen the review success page and completed the lazy registration.'),
        ),
    ]
