# Generated by Django 5.2.4 on 2025-10-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='A unique, URL-friendly version of the title.', unique=True)),
                ('location', models.CharField(default='Remote', max_length=100)),
                ('description', models.TextField(help_text='Full job description. You can use Markdown for formatting.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Uncheck this to hide the job posting from the public site.')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
