from django import forms
from django.utils.translation import gettext_lazy as _
from .models import Property, PropertyUnit, Review, ResidenceLength
from apps.locations.models import Country, State


class PropertySearchForm(forms.Form):
    q = forms.CharField(
        label="Search",
        required=False,
        min_length=3, # Don't search for less than 3 characters
        widget=forms.TextInput(attrs={
            'class': 'form-control me-2',
            'type': 'search',
            'placeholder': 'Search for an Estate, Apartment, or Simply Street...',
            'aria-label': 'Search',
            # HTMX attributes for live search
            'hx-get': '/search/live/', # We will create this URL
            'hx-trigger': 'keyup changed delay:300ms', # Trigger on typing, with a delay
            'hx-target': '#live-search-results', # Put results in this div
            'hx-indicator': '.htmx-indicator', # Show a spinner while loading
        })
    )


class PropertyForm(forms.ModelForm):
    # This field is correct because it's an extra field, not in the model.
    property_search = forms.CharField(
        label=_("Search for your property on Google Maps"),
        required=False,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _("e.g., The Royal Palms or Spring Garden Estate")
        })
    )

    class Meta:
        model = Property
        # This list should contain all the model fields you want to use.
        fields = [
            'name', 'property_type', 'address', 'city',
            'country', 'state', 'postal_code',
            'latitude', 'longitude', 'google_place_id',
        ]
        
        help_texts = {
            'property_type': _("'Stand-alone' indicates that the property is not part of a larger estate or gated community."),
            'name': _("Leave blank if the property does not have a specific name like 'Tsavo Heights' "),
        }

        # The widgets dictionary is the correct place to define the input type.
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'property_type': forms.Select(attrs={'class': 'form-select'}),
            'address': forms.TextInput(attrs={'placeholder': _('e.g., 123 Unity Road')}),
            'city': forms.TextInput(attrs={'placeholder': _('e.g., Birnin Zana')}),
            # These will be rendered as <select> dropdowns
            'country': forms.Select(attrs={'class': 'form-select'}),
            'state': forms.Select(attrs={'class': 'form-select'}),
            'postal_code': forms.TextInput(attrs={'placeholder': _('e.g., 54321')}),
            'latitude': forms.HiddenInput(),
            'longitude': forms.HiddenInput(),
            'google_place_id': forms.HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        """
        The __init__ method is the single source of truth for dynamically
        configuring the fields that are generated by the Meta class.
        """
        super().__init__(*args, **kwargs)

        # --- REQUIRED FIELD CHANGES ---
        
        # Configure Country
        self.fields['country'].queryset = Country.objects.all().order_by('name')
        self.fields['country'].empty_label = _("--- Select a Country ---")
        self.fields['country'].required = True # Explicitly set as required

        # Configure State
        self.fields['state'].queryset = State.objects.none()
        self.fields['state'].empty_label = _("--- Select a Country First ---")
        self.fields['state'].required = True # Explicitly set as required

        # Configure Property Type (This is the corrected line)
        self.fields['property_type'].required = True
        # Convert the choices iterator to a list before concatenating
        self.fields['property_type'].choices = [('', _('--- Select a Property Type ---'))] + list(self.fields['property_type'].choices)

        # Other fields
        self.fields['name'].required = False
        self.fields['address'].required = True

        # This part for handling form errors is still correct
        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['state'].queryset = State.objects.filter(country_id=country_id).order_by('name')
            except (ValueError, TypeError):
                pass

class PropertyUnitForm(forms.ModelForm):
    """
    Form for adding a specific unit (e.g., apartment number) to a property.
    This is intentionally simple and focused.
    """
    class Meta:
        model = PropertyUnit
        # The 'property' relationship is linked in the view logic, not set by the user here.
        fields = ['unit_identifier']
        labels = {
            'unit_identifier': _("Your Unit Identifier"),
        }
        help_texts = {
            'unit_identifier': _("e.g., 'Apartment A521' or 'House 7, Block 10'"),
        }


class ReviewForm(forms.ModelForm):
    """
    Form for the main review content, including all ratings and text feedback.
    """
    class Meta:
        model = Review
        # The 'unit', 'author', and 'status' are all set in the view, not the form.
        fields = [
            'residence_length',
            'security_rating',
            'electricity_rating',
            'water_rating',
            'management_rating',
            'road_network_rating',
            'mobile_network_rating',
            'pros',
            'cons'
        ]
        # Using specific widgets to improve the user experience.
        widgets = {
            'pros': forms.Textarea(attrs={'rows': 5, 'placeholder': _('e.g., Great security, constant power, quiet environment...')}),
            'cons': forms.Textarea(attrs={'rows': 5, 'placeholder': _('e.g., Excessive bills, incompetent management, flooding, frequent water shortages...')}),
        }
        # Clear, question-based labels for better usability.
        labels = {
            'residence_length': _("How long have you lived (or did you live) at this property?"),
            'security_rating': _("How would you rate the security?"),
            'electricity_rating': _("How would you rate the electricity supply?"),
            'water_rating': _("How would you rate the water supply and quality?"),
            'management_rating': _("How would you rate the property management?"),
            'road_network_rating': _("How would you rate the roads, congestion, and drainage?"),
            'mobile_network_rating': _("How would you rate the mobile network for calls and data?"),
            'pros': _("Pros (The good things)"),
            'cons': _("Cons (The bad things)"),
        }