from django import forms
from django.utils.translation import gettext_lazy as _
from .models import Property, PropertyUnit, Review, ResidenceLength, OverallRating
from apps.locations.models import Country, State
from django.urls import reverse
from django.utils.safestring import mark_safe


class PropertySearchForm(forms.Form):
    q = forms.CharField(
        label="Search",
        required=False,
        min_length=3, # Don't search for less than 3 characters
        widget=forms.TextInput(attrs={
            'class': 'form-control me-2',
            'type': 'search',
            'placeholder': 'Search for an Estate, Apartment, or Simply Street...',
            'aria-label': 'Search',
            # HTMX attributes for live search
            'hx-get': '/search/live/', # We will create this URL
            'hx-trigger': 'keyup changed delay:300ms', # Trigger on typing, with a delay
            'hx-target': '#live-search-results', # Put results in this div
            'hx-indicator': '.htmx-indicator', # Show a spinner while loading
        })
    )


class PropertyForm(forms.ModelForm):
    # This field is correct because it's an extra field, not in the model.
    property_search = forms.CharField(
        label=_("Search for your property on Google Maps"),
        required=False,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _("e.g., The Royal Palms or Spring Garden Estate")
        })
    )

    class Meta:
        model = Property
        # This list should contain all the model fields you want to use.
        fields = [
            'name', 'property_type', 'address', 'city',
            'country', 'state', 'postal_code',
            'latitude', 'longitude', 'google_place_id',
        ]
        
        help_texts = {
            'property_type': _("'Stand-alone' indicates that the property is not part of a larger estate or gated community."),
            'name': _("Leave blank if the property does not have a specific name like 'Tsavo Heights' "),
        }

        # The widgets dictionary is the correct place to define the input type.
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'property_type': forms.Select(attrs={'class': 'form-select'}),
            'address': forms.TextInput(attrs={'placeholder': _('e.g., 123 Unity Road')}),
            'city': forms.TextInput(attrs={'placeholder': _('e.g., Birnin Zana')}),
            # These will be rendered as <select> dropdowns
            'country': forms.Select(attrs={'class': 'form-select'}),
            'state': forms.Select(attrs={'class': 'form-select'}),
            'postal_code': forms.TextInput(attrs={'placeholder': _('e.g., 54321')}),
            'latitude': forms.HiddenInput(),
            'longitude': forms.HiddenInput(),
            'google_place_id': forms.HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        """
        The __init__ method is the single source of truth for dynamically
        configuring the fields that are generated by the Meta class.
        """
        super().__init__(*args, **kwargs)

        # --- REQUIRED FIELD CHANGES ---
        
        # Configure Country
        self.fields['country'].queryset = Country.objects.all().order_by('name')
        self.fields['country'].empty_label = _("--- Select a Country ---")
        self.fields['country'].required = True # Explicitly set as required

        # Configure State
        self.fields['state'].queryset = State.objects.none()
        self.fields['state'].empty_label = _("--- Select a Country First ---")
        self.fields['state'].required = True # Explicitly set as required

        # Configure Property Type (This is the corrected line)
        self.fields['property_type'].required = True
        # Convert the choices iterator to a list before concatenating
        self.fields['property_type'].choices = [('', _('--- Select a Property Type ---'))] + list(self.fields['property_type'].choices)

        # Other fields
        self.fields['name'].required = False
        self.fields['address'].required = True

        # This part for handling form errors is still correct
        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['state'].queryset = State.objects.filter(country_id=country_id).order_by('name')
            except (ValueError, TypeError):
                pass
            
    def clean(self):
        cleaned_data = super().clean()
        google_place_id = cleaned_data.get('google_place_id')
        name = cleaned_data.get('name')
        address = cleaned_data.get('address')
        
        # Define the existing property instance
        existing_property = None

        # Scenario 1: User submitted with a Google Place ID
        if google_place_id:
            # Check if a property with this Google ID already exists.
            # This is the most reliable check.
            existing_property = Property.objects.filter(google_place_id=google_place_id).first()

        # Scenario 2: Manual entry (no Google Place ID)
        # We check for a close match on name and address. This is less precise but necessary.
        elif name and address:
            existing_property = Property.objects.filter(name__iexact=name, address__iexact=address).first()

        # If we found an existing property by either method...
        if existing_property:
            # Create the URL to the existing property's detail page.
            detail_url = reverse('reviews:property-detail', kwargs={'pk': existing_property.pk})
            
            # Create a user-friendly, HTML-formatted error message with a link.
            error_message = mark_safe(
                _('This property already exists in our system. '
                  '<a href="{url}" class="alert-link">Click here to view it.</a>')
                .format(url=detail_url)
            )
            
            # Raise a non-field validation error with our custom message.
            raise forms.ValidationError(error_message)
            
        return cleaned_data

class PropertyUnitForm(forms.ModelForm):
    """
    Form for adding a specific unit (e.g., apartment number) to a property.
    This is intentionally simple and focused.
    """
    class Meta:
        model = PropertyUnit
        # The 'property' relationship is linked in the view logic, not set by the user here.
        fields = ['unit_identifier']
        labels = {
            'unit_identifier': _("Your Unit Identifier"),
        }
        help_texts = {
            'unit_identifier': _("e.g., 'Apartment A521' or 'House 7, Block 10'"),
        }


class ReviewForm(forms.ModelForm):
    """
    The main form for creating and editing a review.
    
    This form is architected to be "smart" about its rating fields.
    It programmatically changes their widget to RadioSelect, which is the
    necessary foundation for the custom star-rating UI in the template.
    """
    
    class Meta:
        model = Review
        # The 'unit', 'author', and 'status' are correctly set in the view, not the form.
        fields = [
            'residence_length',
            'security_rating',
            'electricity_rating',
            'water_rating',
            'management_rating',
            'road_network_rating',
            'mobile_network_rating',
            'pros',
            'cons'
        ]
        
        # We define the widget TYPE here. Presentation (like rows/placeholders)
        # is best handled in the template with widget_tweaks for consistency.
        widgets = {
            'pros': forms.Textarea(attrs={'rows': 5, 'placeholder': _('e.g., The water is very clean...')}),
            'cons': forms.Textarea(attrs={'rows': 5, 'placeholder': _('e.g., Taking a walk is dangerous...')}),
        }

        # User-friendly labels are a world-class detail. These are perfect.
        labels = {
            'residence_length': _("How long have you lived (or did you live) here?"),
            'security_rating': _("Security"),
            'electricity_rating': _("Electricity Supply"),
            'water_rating': _("Water Supply & Quality"),
            'management_rating': _("Property Management"),
            'road_network_rating': _("Roads & Access"),
            'mobile_network_rating': _("Mobile Network"),
            'pros': _("Pros"),
            'cons': _("Cons"),
        }

        # # Help texts provide crucial guidance to the user.
        # help_texts = {
        #     'pros': _('e.g., Great security, constant power, quiet environment...'),
        #     'cons': _('e.g., Excessive bills, incompetent management, flooding...'),
        # }
                
    def __init__(self, *args, **kwargs):
        """
        Overrides the default __init__ to dynamically configure all rating fields.
        """
        super().__init__(*args, **kwargs)
        
        for field_name, field in self.fields.items():
            if 'rating' in field_name:
                # --- THE DEFINITIVE FIX ---
                # Create the RadioSelect widget AND give it the correct choices
                # in a single, correct step. This prevents both the blank
                # choice (6th star) and the empty widget (no stars) issues.
                field.widget = forms.RadioSelect(choices=OverallRating.choices)