# Generated by Django 5.2.4 on 2025-07-31 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Property Name')),
                ('address', models.CharField(help_text='Full address of the property', max_length=255)),
                ('google_place_id', models.CharField(blank=True, help_text='Google Places API unique ID.', max_length=255, null=True, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State / Province / Region')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code / ZIP Code')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_CORRECTION', 'Needs Correction')], default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_identifier', models.CharField(help_text="e.g., 'Apartment A521' or 'House 7, Block 10'", max_length=50, verbose_name='Unit Identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='reviews.property', verbose_name='Parent Property')),
            ],
            options={
                'verbose_name': 'Property Unit',
                'verbose_name_plural': 'Property Units',
                'unique_together': {('property', 'unit_identifier')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_rating', models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], verbose_name='Security Rating')),
                ('electricity_rating', models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], verbose_name='Electricity Rating')),
                ('water_rating', models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], verbose_name='Water Rating')),
                ('mobile_network_rating', models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], verbose_name='Mobile Network Rating')),
                ('road_network_rating', models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], verbose_name='Road Network Rating')),
                ('management_rating', models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], verbose_name='Management Rating')),
                ('pros', models.TextField(help_text='What are the best things about living here?', verbose_name='Pros')),
                ('cons', models.TextField(help_text='What are the best things about living here?', verbose_name='Cons')),
                ('status', models.CharField(choices=[('PROP_PENDING', 'Pending Property Approval'), ('CONT_PENDING', 'Pending Content Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('USER_DELETED', 'Deleted by User'), ('ADMIN_REMOVED', 'Removed by Admin')], default='PROP_PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.propertyunit', verbose_name='Property Unit')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
