# Generated by Django 5.2.4 on 2025-08-24 19:14

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Property Name')),
                ('address', models.CharField(help_text='Full address of the property', max_length=255)),
                ('google_place_id', models.CharField(blank=True, help_text='Google Places API unique ID.', max_length=255, null=True, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code / ZIP Code')),
                ('property_type', models.CharField(choices=[('APARTMENT', 'Stand-alone Apartment Building'), ('ESTATE', 'Gated Estate / Community'), ('HOUSE', 'Stand-alone House'), ('OTHER', 'Other')], max_length=20, verbose_name='Type of Property')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_CORRECTION', 'Needs Correction'), ('ADMIN_REMOVED', 'Removed by Admin')], default='PENDING', max_length=20, verbose_name='Status')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_identifier', models.CharField(help_text="e.g., 'Apartment A521' or 'House 7, Block 10'", max_length=50, verbose_name='Unit Identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Property Unit',
                'verbose_name_plural': 'Property Units',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence_length', models.IntegerField(choices=[(6, 'Less than 6 months'), (12, '6 months to 1 year'), (24, '1 - 2 years'), (48, '2 - 4 years'), (60, 'More than 4 years')], verbose_name='How long did you live here?')),
                ('security_rating', models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], verbose_name='Security Rating')),
                ('electricity_rating', models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], verbose_name='Electricity Rating')),
                ('water_rating', models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], verbose_name='Water Rating')),
                ('mobile_network_rating', models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], verbose_name='Mobile Network Rating')),
                ('road_network_rating', models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], verbose_name='Road Network Rating')),
                ('management_rating', models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], verbose_name='Management Rating')),
                ('pros', models.TextField(help_text='What are the best things about living here?', verbose_name='Pros')),
                ('cons', models.TextField(help_text='What are the biggest challenges or worst things about living here?', verbose_name='Cons')),
                ('status', models.CharField(choices=[('PROP_PENDING', 'Pending Property Approval'), ('CONT_PENDING', 'Pending Content Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROP_REJECTED', 'Property Rejected'), ('USER_DELETED', 'Deleted by User'), ('ADMIN_REMOVED', 'Removed by Admin'), ('PROPERTY_REMOVED', 'Associated Property Removed'), ('UNDER_REVIEW', 'Under Review / Quarantined')], default='PROP_PENDING', max_length=20, verbose_name='Status')),
                ('is_author_phone_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')])),
            ],
        ),
    ]
