# Generated by Django 5.2.4 on 2025-08-16 10:36

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.state', verbose_name='State / Province / Region'),
        ),
        migrations.AddField(
            model_name='propertyunit',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='reviews.property', verbose_name='Parent Property'),
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='review',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.propertyunit', verbose_name='Property Unit'),
        ),
        migrations.AddField(
            model_name='vote',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reviews.review'),
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='property',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='reviews_pro_search__ba9123_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyunit',
            unique_together={('property', 'unit_identifier')},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'review')},
        ),
    ]
