# Generated by Django 5.2.4 on 2025-07-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_CORRECTION', 'Needs Correction'), ('ADMIN_REMOVED', 'Removed by Admin')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
    ]
