# Generated by Django 5.2.4 on 2025-09-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='cons',
            field=models.TextField(help_text='What are the unique challenges or worst things about living here?', verbose_name='Cons'),
        ),
    ]
