# Generated by Django 5.2.4 on 2025-08-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedReview',
            fields=[
            ],
            options={
                'verbose_name': 'Flagged Review',
                'verbose_name_plural': ' Flagged Review Queue',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reviews.review',),
        ),
        migrations.CreateModel(
            name='PendingProperty',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Property',
                'verbose_name_plural': '  Property Approval Queue',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reviews.property',),
        ),
        migrations.CreateModel(
            name='PendingReview',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Review',
                'verbose_name_plural': ' Review Content Queue',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reviews.review',),
        ),
    ]
