# Generated by Django 5.2.4 on 2025-09-17 09:11

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_cons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
    ]
