# Generated by Django 5.2.4 on 2025-08-12 14:46

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_helpful_votes_review_is_author_phone_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
    ]
