# Generated by Django 5.2.4 on 2025-07-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('PROP_PENDING', 'Pending Property Approval'), ('CONT_PENDING', 'Pending Content Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROP REJECTED', 'Property Rejected'), ('USER_DELETED', 'Deleted by User'), ('ADMIN_REMOVED', 'Removed by Admin'), ('PROPERTY_REMOVED', 'Associated Property Removed')], default='PROP_PENDING', max_length=20, verbose_name='Status'),
        ),
    ]
