# Generated by Django 5.2.4 on 2025-08-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment Building'), ('ESTATE', 'Gated Estate / Community'), ('HOUSE', 'Stand-alone House'), ('TERRACE', 'Terraced House (e.g., Duplex)'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Type of Property'),
        ),
        migrations.AddField(
            model_name='review',
            name='residence_length',
            field=models.IntegerField(choices=[(6, 'Less than 6 months'), (12, '6 months to 1 year'), (24, '1 - 2 years'), (48, '2 - 4 years'), (60, 'More than 4 years')], default=0, verbose_name='How long did you live here?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('PROP_PENDING', 'Pending Property Approval'), ('CONT_PENDING', 'Pending Content Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROP_REJECTED', 'Property Rejected'), ('USER_DELETED', 'Deleted by User'), ('ADMIN_REMOVED', 'Removed by Admin'), ('PROPERTY_REMOVED', 'Associated Property Removed')], default='PROP_PENDING', max_length=20, verbose_name='Status'),
        ),
    ]
