# Generated by Django 5.2.4 on 2025-09-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_property_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='residence_length',
            field=models.IntegerField(choices=[(6, 'less than 6 months'), (12, '6 months to 1 year'), (24, '1 - 2 years'), (48, '2 - 4 years'), (60, 'more than 4 years')], verbose_name='How long did you live here?'),
        ),
    ]
