# Generated by Django 5.2.4 on 2025-08-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_property_property_type_review_residence_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment Building'), ('ESTATE', 'Gated Estate / Community'), ('HOUSE', 'Stand-alone House'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Type of Property'),
        ),
    ]
