# Generated by Django 5.2.4 on 2025-11-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_residence_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='flooding_severity',
            field=models.CharField(choices=[('NONE', 'No Flooding: The property and access roads remain dry.'), ('EXTERNAL', 'External Only: Access roads flood, but the compound is fine.'), ('COMPOUND', 'Compound Flooding: Water pools in parking/common areas, but does not enter buildings.'), ('CATASTROPHIC', 'Internal Flooding: Water enters the home/building.')], default='None', help_text='Select the most severe flooding you have experienced here.', max_length=20, verbose_name='Flooding During Heavy Rains'),
            preserve_default=False,
        ),
    ]
