# Generated by Django 5.2.4 on 2025-08-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Property Name'),
        ),
    ]
