# Generated by Django 5.2.4 on 2025-11-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_review_flooding_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='flooding_severity',
            field=models.CharField(choices=[('NONE', 'No Flooding: The property and access roads remain dry.'), ('EXTERNAL', 'External Only: Access roads flood, but the compound is fine.'), ('COMPOUND', 'Compound Flooding: Water pools in parking/common areas, but does not enter buildings.'), ('CATASTROPHIC', 'Internal Flooding: Water enters the home/building.')], help_text='How bad is the flooding during heavy rains?', max_length=20, verbose_name='Flooding During Heavy Rains'),
        ),
    ]
