# Generated by Django 5.2.4 on 2025-12-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_review_flooding_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('PROP_PENDING', 'Pending Property Approval'), ('PENDING_SIGNUP', 'Pending User Signup'), ('CONT_PENDING', 'Pending Content Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROP_REJECTED', 'Property Rejected'), ('USER_DELETED', 'Deleted by User'), ('ADMIN_REMOVED', 'Removed by Admin'), ('PROPERTY_REMOVED', 'Associated Property Removed'), ('UNDER_REVIEW', 'Under Review / Quarantined')], default='PROP_PENDING', max_length=20, verbose_name='Status'),
        ),
    ]
