# Generated by Django 5.2.4 on 2025-08-08 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_country_is_active_state_is_active'),
        ('reviews', '0009_convert_country_char_to_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'Stand-alone Apartment Building'), ('ESTATE', 'Gated Estate / Community'), ('HOUSE', 'Stand-alone House'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Type of Property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.state', verbose_name='State / Province / Region'),
        ),
    ]
