# Generated by Django 5.2.4 on 2025-08-08 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_country_is_active_state_is_active'),
        ('reviews', '0010_alter_property_country_alter_property_property_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='locations.country', verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'Stand-alone Apartment Building'), ('ESTATE', 'Gated Estate / Community'), ('HOUSE', 'Stand-alone House'), ('OTHER', 'Other')], max_length=20, verbose_name='Type of Property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.ForeignKey(default=56, on_delete=django.db.models.deletion.PROTECT, to='locations.state', verbose_name='State / Province / Region'),
            preserve_default=False,
        ),
    ]
