# Generated by Django 5.2.4 on 2025-08-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_alter_property_country_alter_property_property_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
    ]
